# Generated by Django 4.0.4 on 2024-03-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={'verbose_name': 'UserLessonProgress', 'verbose_name_plural': 'UserLessonProgresses'},
        ),
    ]
